/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ABOUT_US.java
 *
 * Created on 21 Nov, 2018, 3:46:41 PM
 */

/**
 *
 * @author Manoharan
 */
public class ABOUT_US extends javax.swing.JFrame {

    /** Creates new form ABOUT_US */
    public ABOUT_US() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\IPPROJECT\\IPPROJECT\\images\\whatsapp_2.png")); // NOI18N
        jPanel1.add(jLabel15);
        jLabel15.setBounds(750, 310, 74, 70);

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\IPPROJECT\\IPPROJECT\\images\\facebook_icon.jpeg")); // NOI18N
        jPanel1.add(jLabel14);
        jLabel14.setBounds(640, 400, 180, 170);

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\IPPROJECT\\IPPROJECT\\images\\twitter_icon.png")); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(640, 310, 90, 70);

        jLabel12.setFont(new java.awt.Font("Monospaced", 1, 36));
        jLabel12.setText("THROUGH");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(660, 260, 160, 40);

        jLabel11.setFont(new java.awt.Font("Monospaced", 1, 48));
        jLabel11.setText("ABOUT US");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(60, 140, 260, 90);

        jLabel10.setFont(new java.awt.Font("Monospaced", 1, 18));
        jLabel10.setText("products at the best rate.");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 500, 390, 30);

        jLabel9.setFont(new java.awt.Font("Monospaced", 1, 18));
        jLabel9.setText("on quality and assure you the best");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 460, 390, 30);

        jLabel8.setFont(new java.awt.Font("Monospaced", 1, 18));
        jLabel8.setText("care and so on. We do not compromise");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 420, 400, 30);

        jLabel7.setFont(new java.awt.Font("Monospaced", 1, 18));
        jLabel7.setText("products, fitness products, women");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 380, 390, 30);

        jLabel6.setFont(new java.awt.Font("Monospaced", 1, 18));
        jLabel6.setText("range of other products like baby");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 340, 390, 30);

        jLabel5.setFont(new java.awt.Font("Monospaced", 1, 18));
        jLabel5.setText("best rates and also offer a wide ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 300, 390, 30);

        jButton1.setText("GO BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 540, 100, 25);

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 18));
        jLabel4.setText("deliver the best medicines at the ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 260, 390, 30);

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 18));
        jLabel3.setText("We at Abhishek's Drug Emporium ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 220, 390, 30);

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 36));
        jLabel2.setText("CONTACT US");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(630, 200, 230, 60);

        jLabel16.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        jPanel1.add(jLabel16);
        jLabel16.setBounds(40, 30, 300, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\IPPROJECT\\IPPROJECT\\images\\pharmacy_icon.jpg")); // NOI18N
        jLabel1.setText("asdfghjkl;");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 870, 580);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CUSTOMER_HOME C=new CUSTOMER_HOME();
        C.jLabel7.setText(jLabel16.getText());
        C.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ABOUT_US().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    public static javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
