/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ADMIN_HOME.java
 *
 * Created on 3 Aug, 2018, 9:27:11 PM
 */

/**
 *
 * @author Manoharan
 */
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class ADMIN_HOME extends javax.swing.JFrame {

    /** Creates new form ADMIN_HOME */
    public ADMIN_HOME() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Abhishek's DRUG Emporium");

        jPanel1.setBackground(new java.awt.Color(-65536,true));

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 48));
        jLabel1.setText("Welcome ");

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 48));

        jButton1.setBackground(new java.awt.Color(-16711681,true));
        jButton1.setText("MEDICINE STOCK INVENTORY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(-256,true));
        jButton2.setText("ADD MEDICINES");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(-16711936,true));
        jButton3.setText("PROFILE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(-16776961,true));
        jButton4.setText("LOGOUT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\IPPROJECT\\IPPROJECT\\images\\pharmacy 3.jpg")); // NOI18N

        jButton5.setBackground(new java.awt.Color(-4144960,true));
        jButton5.setText("MODIFY MEDICINE DETAILS");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(-14336,true));
        jButton6.setText("REMOVE MEDICINES");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(91, 91, 91)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(54, 54, 54)
                                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jButton2)
                        .addGap(29, 29, 29)
                        .addComponent(jButton5)
                        .addGap(28, 28, 28)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton2)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int n=JOptionPane.showConfirmDialog(null,"Do you want to logout ? ");
        if(n==0){
        new SIGN_IN_ADMIN().setVisible(true);
        this.setVisible(false);}
 
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MEDICINES_ADMIN m=new MEDICINES_ADMIN();
        try{
           Class.forName("java.sql.DriverManager");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost/ipproject","root","muruga123");
           Statement st=con.createStatement();
           
           ResultSet rs=st.executeQuery("SELECT DISTINCT * FROM MEDICINES");
           while(rs.next()){
               String a=rs.getString("MEDID");
                String b=rs.getString("MEDNAME");
                String c=rs.getString("MEDFUNC");
                String d=rs.getString("MEDCOMP");
                String e=rs.getString("MEDPRICE");
                String f=rs.getString("MEDMFD");
                String g=rs.getString("MEDEXP");
                String h=rs.getString("MEDMANF");
                String i=rs.getString("MEDDOSE");
                String j=rs.getString("SCHEDULEDHDRUG");
                String k=rs.getString("STOCK");
           DefaultTableModel n=(DefaultTableModel)m.jTable1.getModel();
           n.addRow(new Object[] {a,b,c,d,e,f,g,h,i,j,k} );
           }
           m.jLabel1.setText(jLabel2.getText());
           m.jLabel1.setHorizontalAlignment(SwingConstants.CENTER);

        m.setVisible(true);
        this.setVisible(false);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         MEDICINES_ADMIN_MODIFIER M=new MEDICINES_ADMIN_MODIFIER();
        M.setVisible(true);
        M.jLabel13.setText(jLabel2.getText());
        M.jButton2.setVisible(false);
        M.jButton4.setVisible(false);
        M.jButton1.setVisible(false);
        M.jButton6.setVisible(false);
        M.jLabel1.setVisible(false);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ADMIN_DETAILS A=new ADMIN_DETAILS();
        try{
          Class.forName("java.sql.DriverManager");
          Connection con=DriverManager.getConnection("jdbc:mysql://localhost/ipproject","root","muruga123");
          Statement st=con.createStatement();
          Statement st1=con.createStatement();
          ResultSet rs=st.executeQuery("SELECT * FROM ADMIN WHERE ADMINNAME='"+jLabel2.getText()+"'");
          if(rs.next()){
              String a=rs.getString("ADMINNO");
              String b=rs.getString("ADMINNAME");
              String c=rs.getString("ADMINAGE");
              String d=rs.getString("ADMINGENDER");
              String e=rs.getString("ADMINDEPT");
              String f=rs.getString("ADMINMOB");
              String g=rs.getString("ADMINADD");
              String h=rs.getString("ADMINMAIL");

              A.jTextField1.setText(a);
              A.jTextField2.setText(b);
              A.jTextField3.setText(c);
              A.jTextField4.setText(d);
              A.jTextField5.setText(e);
              A.jTextField6.setText(f);
              A.jTextField7.setText(g);
              A.jTextField8.setText(h);

              ResultSet rs1=st1.executeQuery("SELECT * FROM USERS WHERE EMAILID='"+h+"'");
              if(rs1.next()){
                  A.jTextField9.setText(rs1.getString("USERNAME"));
                  A.jTextField10.setText(rs1.getString("PASSWORD"));
              }
          }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        A.jButton4.setVisible(false);
        A.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
MEDICINES_ADMIN_MODIFIER M=new MEDICINES_ADMIN_MODIFIER();
        M.setVisible(true);
        M.jLabel13.setText(jLabel2.getText());
        M.jButton2.setVisible(false);
        M.jButton3.setVisible(false);
        M.jButton4.setVisible(false);
        M.jButton5.setVisible(false);
       
        M.jTextField1.setVisible(false);
        M.jTextField2.setVisible(false);
        M.jTextField4.setVisible(false);
        M.jTextField5.setVisible(false);
        M.jTextField6.setVisible(false);
        M.jTextField7.setVisible(false);
        M.jTextField8.setVisible(false);
        M.jTextField3.setVisible(false);
        M.jTextField10.setVisible(false);
        M.jButton6.setVisible(false);
        M.jLabel2.setVisible(false);
        M.jLabel4.setVisible(false);
        M.jLabel5.setVisible(false);
        M.jLabel6.setVisible(false);
        M.jLabel8.setVisible(false);
        M.jLabel9.setVisible(false);
        M.jLabel7.setVisible(false);
        M.jLabel10.setVisible(false);
        M.jLabel11.setVisible(false);
       
        M.jRadioButton1.setVisible(false);
        M.jRadioButton2.setVisible(false);

        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
       MEDICINES_ADMIN_MODIFIER M=new MEDICINES_ADMIN_MODIFIER();
        M.setVisible(true);
        M.jLabel13.setText(jLabel2.getText());
        M.jButton1.setVisible(false);
        M.jButton3.setVisible(false);
        M.jButton4.setVisible(false);
        M.jButton5.setVisible(false);
       
        M.jTextField1.setVisible(false);
        M.jTextField2.setVisible(false);
        M.jTextField4.setVisible(false);
        M.jTextField5.setVisible(false);
        M.jTextField6.setVisible(false);
        M.jTextField7.setVisible(false);
        M.jTextField8.setVisible(false);
        M.jTextField3.setVisible(false);
        M.jTextField10.setVisible(false);
        M.jButton6.setVisible(false);
        M.jLabel2.setVisible(false);
        M.jLabel4.setVisible(false);
        M.jLabel5.setVisible(false);
        M.jLabel6.setVisible(false);
        M.jLabel8.setVisible(false);
        M.jLabel9.setVisible(false);
        M.jLabel7.setVisible(false);
        M.jLabel10.setVisible(false);
        M.jLabel11.setVisible(false);
        M.jLabel1.setText("ENTER ID OF MEDICINE TO BE DELETED");
        M.jRadioButton1.setVisible(false);
        M.jRadioButton2.setVisible(false);

        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADMIN_HOME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
