
import javax.swing.SwingConstants;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CUSTOMER_CART.java
 *
 * Created on 1 Oct, 2018, 5:33:54 PM
 */

/**
 *
 * @author Manoharan
 */
import javax.swing.*;
import java.sql.*;

import java.util.Date;
import javax.swing.table.DefaultTableModel;
public class CUSTOMER_CART extends javax.swing.JFrame {
         static String amt;

    /** Creates new form CUSTOMER_CART */
    public CUSTOMER_CART() {
        
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(-16711681,true));

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 48));
        jLabel2.setText("ITEMS IN YOUR CART");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SNO.", "NAME", "COMPOSITION", "PRICE(per unit)", "MFD", "EXP", "MANUFACTURER", "DOSE", "SCHEDULEDHDRUG", "QUANTITY", "TOTAL"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 48));
        jLabel3.setText("CART");

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 36));
        jLabel4.setText("TOTAL PRICE : ");

        jTextField1.setFont(new java.awt.Font("Monospaced", 1, 36));

        jButton1.setBackground(new java.awt.Color(-16777216,true));
        jButton1.setFont(new java.awt.Font("Monospaced", 1, 36));
        jButton1.setForeground(new java.awt.Color(-1,true));
        jButton1.setText("GO BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(-16776961,true));
        jButton2.setFont(new java.awt.Font("Monospaced", 1, 36));
        jButton2.setForeground(new java.awt.Color(-1,true));
        jButton2.setText("PROCEED TO CHECKOUT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Monospaced", 1, 48));
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(-16777216,true)));

        jButton3.setText("DELETE AN ITEM");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("CHANGE QUANTITY");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1401, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(115, 115, 115)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(664, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(645, 645, 645)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(496, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(437, 437, 437)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(jLabel3)
                    .addContainerGap(441, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(442, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(23, 23, 23)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         CUSTOMER_BUY C=new CUSTOMER_BUY();
        C.jLabel6.setText(jLabel6.getText());
        C.jLabel6.setHorizontalAlignment(SwingConstants.CENTER);
        try{
           Class.forName("java.sql.DriverManager");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost/ipproject","root","muruga123");
           Statement st=con.createStatement();

           ResultSet rs=st.executeQuery("SELECT DISTINCT * FROM MEDICINES");
           while(rs.next()){
               String a=rs.getString("MEDID");
                String b=rs.getString("MEDNAME");
                String c=rs.getString("MEDFUNC");
                String d=rs.getString("MEDCOMP");
                String e=rs.getString("MEDPRICE");
                String f=rs.getString("MEDMFD");
                String g=rs.getString("MEDEXP");
                String h=rs.getString("MEDMANF");
                String i=rs.getString("MEDDOSE");
                String j=rs.getString("SCHEDULEDHDRUG");
           DefaultTableModel n=(DefaultTableModel)C.jTable1.getModel();
           n.addRow(new Object[] {a,b,c,d,e,f,g,h,i,j} );
           }
        }
         catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        C.setVisible(true);
        this.setVisible(false);



        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int a=jTable1.getSelectedRow();
        if(a==-1) JOptionPane.showMessageDialog(null,"Please select the item you want to delete");
        int b=Integer.parseInt(jTable1.getValueAt(a,0).toString());
        int c=JOptionPane.showConfirmDialog(null, "Do you want to delete the selected item from your cart ?");
        if(c==0){
        try{
            Class.forName("java.sql.DriverManager");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/ipproject","root","muruga123");
            Statement st=con.createStatement();
            Statement st1=con.createStatement();
            int n=st1.executeUpdate("DELETE FROM CART WHERE SNO="+b);
            if(n==1) JOptionPane.showMessageDialog(null, "Item deleted successfully");

             ResultSet rs=st.executeQuery("SELECT * FROM CART");
           while(rs.next()){
                rs.first();
                String m=rs.getString("SNO");
                String o=rs.getString("MEDNAME");
                String d=rs.getString("MEDCOMP");
                String e=rs.getString("MEDPRICE");
                String f=rs.getString("MEDMFD");
                String g=rs.getString("MEDEXP");
                String h=rs.getString("MEDMANF");
                String i=rs.getString("MEDDOSE");
                String j=rs.getString("SCHEDULEDHDRUG");
                String k=rs.getString("QUANTITY");
                String l=rs.getString("TOTAL");
           DefaultTableModel p=(DefaultTableModel)jTable1.getModel();
           p.setRowCount(0);
           p.addRow(new Object[] {m,o,d,e,f,g,h,i,j,k,l} );
           int q=0;
         double sum=0;
         int r=jTable1.getRowCount();
         while(q<r){
         double s=Double.parseDouble(jTable1.getValueAt(q,10).toString());
         sum=sum+s;
         q++;
           }
         jTextField1.setText(sum+"");
           }
             amt = jTextField1.getText();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int a=jTable1.getSelectedRow();
        if(a==-1) JOptionPane.showMessageDialog(null,"Please select the item whose quantity you want to change");
        int b=Integer.parseInt(jTable1.getValueAt(a,0).toString());
        int c=Integer.parseInt(JOptionPane.showInputDialog("Enter the quantity of the selected item you want"));
        
        try{
            Class.forName("java.sql.DriverManager");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/ipproject","root","muruga123");
            Statement st=con.createStatement();
            Statement st1=con.createStatement();
            DefaultTableModel su=(DefaultTableModel) jTable1.getModel();
            String sa=su.getValueAt(0, 3).toString();
            double mat=c*(Double.parseDouble(sa));
            int n=st1.executeUpdate("UPDATE CART SET QUANTITY="+c+" WHERE SNO="+b);
            if(n==1) JOptionPane.showMessageDialog(null, "Item modified successfully");
            Statement st2=con.createStatement();
            int z=st2.executeUpdate("UPDATE CART SET TOTAL="+mat+" WHERE SNO="+b);
             ResultSet rs=st.executeQuery("SELECT * FROM CART");
           while(rs.next()){
                boolean first = rs.first();
                if(first==true){
                String m=rs.getString("SNO");
                String o=rs.getString("MEDNAME");
                String d=rs.getString("MEDCOMP");
                String e=rs.getString("MEDPRICE");
                String f=rs.getString("MEDMFD");
                String g=rs.getString("MEDEXP");
                String h=rs.getString("MEDMANF");
                String i=rs.getString("MEDDOSE");
                String j=rs.getString("SCHEDULEDHDRUG");
                String k=rs.getString("QUANTITY");
                String l=rs.getString("TOTAL");
           DefaultTableModel p=(DefaultTableModel)jTable1.getModel();
           p.setRowCount(0);
           p.addRow(new Object[] {m,o,d,e,f,g,h,i,j,k,l} );
           int q=0;
         double sum=0;
         int r=jTable1.getRowCount();
         while(q<r){
         double s=Double.parseDouble(jTable1.getValueAt(q,10).toString());
         sum=sum+s;
         q++;
           }
         jTextField1.setText(sum+"");
           }
            }
             amt = jTextField1.getText();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            int a=1;
            Class.forName("java.sql.DriverManager");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/ipproject","root","muruga123");
            Statement st=con.createStatement();

            ResultSet rs=st.executeQuery("SELECT * FROM ORDERS");
            if(rs.next()){
                rs.last();
                if(rs.getString("ORDERID").equalsIgnoreCase(null)) a=1;
                else a=(Integer.parseInt(rs.getString("ORDERID"))+1);
            }
            Statement st1=con.createStatement();
            Statement st9=con.createStatement();
            Statement st12=con.createStatement();
            String d="";
            ResultSet rs3=st12.executeQuery("SELECT CURDATE() AS DATE");
            if(rs3.next()) d=rs3.getString("DATE");
            String h=d.substring(8,10);
            int j=Integer.parseInt(h);
            int k=j+2;
            String y="",l="";
            int z=0,w=0;
            if(k<10){
                y="0".concat(k+"");
                l=d.replace(d.substring(8,10),y);
            }
            else if(k>31) {
                y=(k-31)+"";
                z=Integer.parseInt(d.substring(5,7));
                w=z+1;
                String x=(w+"").concat("-").concat(y+"");
                l=d.replace(d.substring(5,10),x);
            }
            else{
                l=d.replace(d.substring(8,10),(k+""));
            }
            

            DefaultTableModel m=(DefaultTableModel)jTable1.getModel();
            
            int i=m.getRowCount();
            String s=m.getValueAt((i-1),0).toString();
            int n=st.executeUpdate("INSERT INTO ORDERS VALUES("+a+",'"+jLabel6.getText()+"',"+jTextField1.getText()+",'"+d+"','"+l+"',"+s+")");
            if(n==1){
                CUSTOMER_BILL C=new CUSTOMER_BILL();
                DefaultTableModel m1=(DefaultTableModel)C.jTable1.getModel();
                ResultSet rs1=st1.executeQuery("SELECT * FROM ORDERS WHERE ORDERID="+a);
                if(rs1.next()){
                String st2=rs1.getString("ORDERID");
                String st3=rs1.getString("CUSNAME");
                String st4=rs1.getString("ORDERPRICE");
                String st5=rs1.getString("PLACEDATE");
                String st6=rs1.getString("DELIVERYDATE");
                String st7=rs1.getString("NOOFITEMS");
                

                m1.addRow(new Object[] {st2,st3,st4,st5,st6,st7});
                C.jTextField4.setText(st2);
                C.jTextField1.setText(st3);
                String st10="",st11="";
                ResultSet rs2=st9.executeQuery("SELECT C.CUSADD,C.CUSMOB FROM CUSTOMER C,ORDERS O WHERE C.CUSNAME=O.CUSNAME");
                if(rs2.next()){
                    st10=rs2.getString("C.CUSADD");
                    st11=rs2.getString("C.CUSMOB");
                }
                C.jTextArea1.setText(st10);
                C.jTextField3.setText(st11);
                }
                C.setVisible(true);
                amt=jTextField1.getText();
                this.setVisible(false);
            }
 else{
                JOptionPane.showMessageDialog(null,"Error 404 : Not Found\nPlease try again Later");
 }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CUSTOMER_CART().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    public static javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
