/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CUSTOMER_HOME.java
 *
 * Created on 29 Jun, 2018, 10:45:19 PM
 */

/**
 *
 * @author Manoharan
 */
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class CUSTOMER_HOME extends javax.swing.JFrame {
public static String Z;

    /** Creates new form CUSTOMER_HOME */
    public CUSTOMER_HOME() {
        initComponents();
Z=jLabel7.getText();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Abhishek's DRUG Emporium");

        jPanel1.setBackground(new java.awt.Color(-16711681,true));

        jLabel6.setFont(new java.awt.Font("Monospaced", 1, 48));
        jLabel6.setText("Welcome");

        jLabel7.setFont(new java.awt.Font("Monospaced", 1, 48));

        jButton1.setText("VIEW MEDICINES AVAILABLE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MY ACCOUNT", "MY ORDERS", "LOGOUT" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton2.setText("PLACE AN ORDER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\IPPROJECT\\IPPROJECT\\images\\pharmacy 4.jpg")); // NOI18N

        jButton3.setText("ABOUT US");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("GIVE US YOUR FEEDBACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, 0, 118, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        int z=jComboBox1.getSelectedIndex();
        if(z==2){
            int n=JOptionPane.showConfirmDialog(null,"Are you sure you wan't to logout ?");
            if(n==0){
                new SIGN_IN_CUSTOMER().setVisible(true);
                this.setVisible(false);
            }
        }
 else if(z==1){
      CUSTOMER_ORDER_HISTORY C=new CUSTOMER_ORDER_HISTORY();
         C.jLabel4.setText(jLabel7.getText());
         C.jLabel4.setHorizontalAlignment(SwingConstants.CENTER);
         try{
              Class.forName("java.sql.DriverManager");
              Connection con=DriverManager.getConnection("jdbc:mysql://localhost/ipproject","root","muruga123");
              Statement st8=con.createStatement();
              Statement st9=con.createStatement();
              ResultSet rs1=st9.executeQuery("SELECT * FROM ORDERS WHERE CUSNAME='"+jLabel7.getText()+"'");
              while(rs1.next()){
                  DefaultTableModel x=(DefaultTableModel)C.jTable2.getModel();
                  String ts1=rs1.getString("ORDERID");
                  String ts2=rs1.getString("CUSNAME");
                  String ts3=rs1.getString("ORDERPRICE");
                  String ts4=rs1.getString("PLACEDATE");
                  String ts5=rs1.getString("DELIVERYDATE");
                  String ts6=rs1.getString("NOOFITEMS");
                

                  x.addRow(new Object[] {ts1,ts2,ts3,ts4,ts5,ts6});
              }
              ResultSet rs=st8.executeQuery("SELECT CURDATE() AS DATE");
              String s="";
              if(rs.next()) s=rs.getString("DATE");
              int r=Integer.parseInt(Character.toString(s.charAt(8)).concat(Character.toString(s.charAt(9))));
                    
                    int n=C.jTable2.getRowCount();
                    DefaultTableModel m=(DefaultTableModel)C.jTable2.getModel();
                    C.setVisible(true);
                    this.setVisible(false);
 }
         catch(Exception e){
             JOptionPane.showMessageDialog(null, e.getMessage());
         }
 }

 else if(z==0){
     CUSTOMER_DETAILS C=new CUSTOMER_DETAILS();
          try{
          Class.forName("java.sql.DriverManager");
          Connection con=DriverManager.getConnection("jdbc:mysql://localhost/ipproject","root","muruga123");
          Statement st=con.createStatement();
          Statement st1=con.createStatement();
          ResultSet rs=st.executeQuery("SELECT * FROM CUSTOMER WHERE CUSNAME='"+jLabel7.getText()+"'");
          if(rs.next()){
              String a=rs.getString("CUSNAME");
              String b=rs.getString("CUSAGE");
              String c=rs.getString("CUSGENDER");
              String d=rs.getString("CUSMOB");
              String e=rs.getString("CUSADD");
              String f=rs.getString("CUSMAIL");
            

              C.jTextField1.setText(a);
              C.jTextField2.setText(b);
              C.jTextField3.setText(c);
              C.jTextField4.setText(d);
              C.jTextField5.setText(e);
              C.jTextField6.setText(f);
              

              ResultSet rs1=st1.executeQuery("SELECT * FROM USERS WHERE EMAILID='"+f+"'");
              if(rs1.next()){
                  C.jTextField9.setText(rs1.getString("USERNAME"));
                  C.jTextField10.setText(rs1.getString("PASSWORD"));
              }
          }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
         C.jTextField1.setEditable(false);
         C.jTextField2.setEditable(false);
        C.jTextField3.setEditable(false);
        C.jTextField4.setEditable(false);
        C.jTextField5.setEditable(false);
        C.jTextField6.setEditable(false);

        C.jButton4.setVisible(false);

        C.setVisible(true);
        this.setVisible(false);



 }
        Z=jLabel7.getText();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MEDICINES_CUSTOMER m=new MEDICINES_CUSTOMER();
        try{
           Class.forName("java.sql.DriverManager");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost/ipproject","root","muruga123");
           Statement st=con.createStatement();

           ResultSet rs=st.executeQuery("SELECT DISTINCT * FROM MEDICINES");
           while(rs.next()){
               String a=rs.getString("MEDID");
                String b=rs.getString("MEDNAME");
                String c=rs.getString("MEDFUNC");
                String d=rs.getString("MEDCOMP");
                String e=rs.getString("MEDPRICE");
                String f=rs.getString("MEDMFD");
                String g=rs.getString("MEDEXP");
                String h=rs.getString("MEDMANF");
                String i=rs.getString("MEDDOSE");
                String j=rs.getString("SCHEDULEDHDRUG");
           DefaultTableModel n=(DefaultTableModel)m.jTable1.getModel();
           n.addRow(new Object[] {a,b,c,d,e,f,g,h,i,j} );
           }
         m.jLabel1.setText(jLabel7.getText());
           m.jLabel1.setHorizontalAlignment(SwingConstants.CENTER);

        m.setVisible(true);
        this.setVisible(false);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        Z=jLabel7.getText();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CUSTOMER_BUY C=new CUSTOMER_BUY();
        C.jLabel6.setText(jLabel7.getText());
        C.jLabel6.setHorizontalAlignment(SwingConstants.CENTER);
        try{
           Class.forName("java.sql.DriverManager");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost/ipproject","root","muruga123");
           Statement st=con.createStatement();

           ResultSet rs=st.executeQuery("SELECT DISTINCT * FROM MEDICINES");
           while(rs.next()){
               String a=rs.getString("MEDID");
                String b=rs.getString("MEDNAME");
                String c=rs.getString("MEDFUNC");
                String d=rs.getString("MEDCOMP");
                String e=rs.getString("MEDPRICE");
                String f=rs.getString("MEDMFD");
                String g=rs.getString("MEDEXP");
                String h=rs.getString("MEDMANF");
                String i=rs.getString("MEDDOSE");
                String j=rs.getString("SCHEDULEDHDRUG");
           DefaultTableModel n=(DefaultTableModel)C.jTable1.getModel();
           n.addRow(new Object[] {a,b,c,d,e,f,g,h,i,j} );
           }
        }
         catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        Z=jLabel7.getText();
        C.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ABOUT_US A=new ABOUT_US();
        A.jLabel16.setText(jLabel7.getText());
        A.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        FEEDBACK F=new FEEDBACK();
        F.jLabel3.setText(jLabel7.getText());
        F.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CUSTOMER_HOME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
