


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PAYMENT_GATEWAY.java
 *
 * Created on 7 Jul, 2018, 10:26:58 PM
 */

/**
 *
 * @author Manoharan
 */
import java.awt.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;

public class PAYMENT_GATEWAY extends javax.swing.JFrame {
        
    /** Creates new form PAYMENT_GATEWAY */
    public PAYMENT_GATEWAY() {
        initComponents();
        jRadioButton1.setActionCommand("IOB");
        jRadioButton2.setActionCommand("ICICI");
        jRadioButton3.setActionCommand("SBI");
        jRadioButton4.setActionCommand("CANARA");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField2 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Abhishek's DRUG Emporium");

        jPanel1.setBackground(new java.awt.Color(-1,true));

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 48));
        jLabel1.setText("PAYMENT GATEWAY");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButton1.setText("NET BANKING");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CREDIT CARD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("DEBIT CARD");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("CASH ON DELIVERY");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(-1,true));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 24));
        jLabel3.setText("ENTER CREDIT CARD NUMBER : ");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(40, 10, 484, 50);

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 24));
        jLabel4.setText("EXPIRY DATE : ");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(40, 130, 250, 42);

        jComboBox1.setFont(new java.awt.Font("Monospaced", 0, 24));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MM", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(40, 180, 94, 39);

        jComboBox2.setFont(new java.awt.Font("Monospaced", 0, 24));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "YY", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050", "2051", "2052", "2053" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox2);
        jComboBox2.setBounds(140, 180, 96, 38);

        jLabel5.setFont(new java.awt.Font("Monospaced", 1, 24));
        jLabel5.setText("CVV : ");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(40, 230, 250, 42);

        jButton5.setText("PAY NOW");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(370, 380, 180, 40);

        jPasswordField1.setFont(new java.awt.Font("Monospaced", 0, 24));
        jPanel2.add(jPasswordField1);
        jPasswordField1.setBounds(40, 270, 370, 50);

        jTextField2.setFont(new java.awt.Font("Monospaced", 0, 24));
        jPanel2.add(jTextField2);
        jTextField2.setBounds(40, 60, 373, 51);

        jRadioButton1.setBackground(new java.awt.Color(-1,true));
        buttonGroup1.add(jRadioButton1);
        jPanel2.add(jRadioButton1);
        jRadioButton1.setBounds(30, 70, 30, 60);

        jRadioButton2.setBackground(new java.awt.Color(-1,true));
        buttonGroup1.add(jRadioButton2);
        jPanel2.add(jRadioButton2);
        jRadioButton2.setBounds(270, 0, 40, 180);

        jRadioButton3.setBackground(new java.awt.Color(-1,true));
        buttonGroup1.add(jRadioButton3);
        jPanel2.add(jRadioButton3);
        jRadioButton3.setBounds(10, 250, 25, 70);

        jRadioButton4.setBackground(new java.awt.Color(-1,true));
        buttonGroup1.add(jRadioButton4);
        jPanel2.add(jRadioButton4);
        jRadioButton4.setBounds(260, 190, 25, 110);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\IPPROJECT\\IPPROJECT\\images\\icici-bank.png")); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6);
        jLabel6.setBounds(330, -10, 200, 200);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\IPPROJECT\\IPPROJECT\\images\\canara-bank.jpg")); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel9);
        jLabel9.setBounds(280, 150, 280, 270);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\IPPROJECT\\IPPROJECT\\images\\sbi-bank.png")); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel7);
        jLabel7.setBounds(40, 210, 210, 180);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\IPPROJECT\\IPPROJECT\\images\\iob-bank.jpg")); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8);
        jLabel8.setBounds(70, -50, 180, 320);

        jLabel11.setBackground(new java.awt.Color(-1,true));
        jLabel11.setFont(new java.awt.Font("Monospaced", 1, 24));
        jLabel11.setText("through cash at the time of delivery");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(20, 120, 520, 40);

        jLabel10.setBackground(new java.awt.Color(-1,true));
        jLabel10.setFont(new java.awt.Font("Monospaced", 1, 24));
        jLabel10.setText("Check this box to confirm your payment");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(20, 100, 540, 33);

        jCheckBox1.setBackground(new java.awt.Color(-1,true));
        jCheckBox1.setFont(new java.awt.Font("Monospaced", 1, 36));
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox1);
        jCheckBox1.setBounds(0, 100, 25, 60);

        jButton6.setText("PAY NOW");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(370, 380, 180, 40);

        jButton7.setText("PAY NOW");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7);
        jButton7.setBounds(370, 380, 180, 40);

        jButton8.setText("PAY NOW");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8);
        jButton8.setBounds(370, 380, 180, 40);

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 36));
        jLabel2.setText("SELECT MODE OF PAYMENT");

        jLabel12.setFont(new java.awt.Font("Monospaced", 1, 24));
        jLabel12.setText("SELECT A BANK");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jLabel12.setVisible(true);
        jPanel2.setVisible(true);
        jCheckBox1.setVisible(false);
          jLabel10.setVisible(false);
       jLabel11.setVisible(false);
        jLabel6.setVisible(true);
        jLabel7.setVisible(true);
        jLabel8.setVisible(true);
        jLabel9.setVisible(true);
        jRadioButton1.setVisible(true);
        jRadioButton2.setVisible(true);
        jRadioButton3.setVisible(true);
        jRadioButton4.setVisible(true);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jComboBox1.setVisible(false);
        jComboBox2.setVisible(false);
        jPasswordField1.setVisible(false);
        jTextField2.setVisible(false);
        jButton6.setVisible(false);
        jButton7.setVisible(false);
        jButton8.setVisible(false);
        jButton5.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jLabel6.setVisible(false);
        jLabel12.setVisible(false);
        jCheckBox1.setVisible(false);
          jLabel10.setVisible(false);
       jLabel11.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        jRadioButton1.setVisible(false);
        jRadioButton2.setVisible(false);
        jRadioButton3.setVisible(false);
        jRadioButton4.setVisible(false);
        jPanel2.setVisible(true);
        jLabel3.setVisible(true);
        jLabel4.setVisible(true);
        jLabel5.setVisible(true);
        jComboBox1.setVisible(true);
        jComboBox2.setVisible(true);
        jPasswordField1.setVisible(true);
        jTextField2.setVisible(true);
        jLabel3.setText("ENTER CREDIT CARD NUMBER");
        jButton5.setVisible(false);
        jButton7.setVisible(false);
        jButton8.setVisible(false);
        jButton6.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         jLabel6.setVisible(false);
           jLabel10.setVisible(false);
           jLabel12.setVisible(false);
       jLabel11.setVisible(false);
        jLabel7.setVisible(false);
        jCheckBox1.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        jRadioButton1.setVisible(false);
        jRadioButton2.setVisible(false);
        jRadioButton3.setVisible(false);
        jRadioButton4.setVisible(false);
        jPanel2.setVisible(true);
        jLabel3.setVisible(true);
        jLabel4.setVisible(true);
        jLabel5.setVisible(true);
        jComboBox1.setVisible(true);
        jComboBox2.setVisible(true);
        jPasswordField1.setVisible(true);
        jTextField2.setVisible(true);
        jLabel3.setText("ENTER DEBIT CARD NUMBER");
        jButton6.setVisible(false);
        jButton5.setVisible(false);
        jButton8.setVisible(false);
        jButton7.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jCheckBox1.setVisible(true);
       jLabel10.setVisible(true);
       jLabel11.setVisible(true);
       jLabel12.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        jRadioButton1.setVisible(false);
        jRadioButton2.setVisible(false);
        jRadioButton3.setVisible(false);
        jRadioButton4.setVisible(false);
        jPanel2.setVisible(true);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jComboBox1.setVisible(false);
        jComboBox2.setVisible(false);
        jPasswordField1.setVisible(false);
        jTextField2.setVisible(false);
        jButton6.setVisible(false);
        jButton7.setVisible(false);
        jButton5.setVisible(false);
        jButton8.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed
int i=1;
    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
           boolean b;
        if(i%2!=0) b=true;
        else b=false;
        jRadioButton2.setSelected(b);
        i++;
    }//GEN-LAST:event_jLabel6MouseClicked
int j=1;
    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
         boolean b;
        if(j%2!=0) b=true;
        else b=false;
        jRadioButton3.setSelected(b);
        j++;
    }//GEN-LAST:event_jLabel7MouseClicked
int k=1;
    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
         boolean b;
        if(k%2!=0) b=true;
        else b=false;
        jRadioButton1.setSelected(b);
        k++;
    }//GEN-LAST:event_jLabel8MouseClicked
int l=1;
    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
         boolean b;
        if(l%2!=0) b=true;
        else b=false;
        jRadioButton4.setSelected(b);
        l++;
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String a=buttonGroup1.getSelection().getActionCommand();
        if(a.equalsIgnoreCase("IOB")){
        IOB_SIGN_IN I=new IOB_SIGN_IN();
        I.setVisible(true);
        this.setVisible(false);
        }
 else if(a.equalsIgnoreCase("ICICI")){
ICICI_SIGN_IN I=new ICICI_SIGN_IN();
        I.setVisible(true);
        this.setVisible(false);
 }
 else if(a.equalsIgnoreCase("SBI")){
SBI_SIGN_IN I=new SBI_SIGN_IN();
        I.setVisible(true);
        this.setVisible(false);
 }
 else if(a.equalsIgnoreCase("CANARA")){
CANARA_SIGN_IN I=new CANARA_SIGN_IN();
        I.setVisible(true);
        this.setVisible(false);
 }
 else JOptionPane.showMessageDialog(null,"SELECT A VALID BANK");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed
int z=1;
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String a=jComboBox1.getSelectedItem().toString();
        String b=jComboBox2.getSelectedItem().toString();
        try{
            Class.forName("java.sql.DriverManager");
            Connection con1=DriverManager.getConnection("jdbc:mysql://localhost/ipproject","root","muruga123");
            Statement st8=con1.createStatement();
            ResultSet rs=st8.executeQuery("SELECT * FROM CREDITCARD WHERE CVV="+new String(jPasswordField1.getPassword()));
            if(rs.next()){
                int c=Integer.parseInt(rs.getString("EXPMM"));
                String d="";
                if(c<10) d="0".concat(c+"");

        if(jTextField2.getText().equalsIgnoreCase(rs.getString("CARDNO")) && a.equalsIgnoreCase(d) && b.equalsIgnoreCase(rs.getString("EXPYYYY"))){
            JOptionPane.showMessageDialog(null,"Payment successful");
            AFTER_PAYMENT C=new AFTER_PAYMENT();
                try{
                     Class.forName("java.sql.DriverManager");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/ipproject","root","muruga123");
            Statement st=con.createStatement();
            Statement ts=con.createStatement();
            String xe="";
            ResultSet sr=ts.executeQuery("SELECT * FROM ORDERS");
            if(sr.last()){
                sr.last();
                xe=sr.getString("ORDERID");
            }
                DefaultTableModel m1=(DefaultTableModel)C.jTable1.getModel();
                
                
                ResultSet rs1=st.executeQuery("SELECT * FROM ORDERS WHERE ORDERID="+xe);
                if(rs1.next()){
                String st2=rs1.getString("ORDERID");
                String st3=rs1.getString("CUSNAME");
                String st4=rs1.getString("ORDERPRICE");
                String st5=rs1.getString("PLACEDATE");
                String st6=rs1.getString("DELIVERYDATE");
                String st7=rs1.getString("NOOFITEMS");
           
                m1.addRow(new Object[] {st2,st3,st4,st5,st6,st7});
            Statement t=con.createStatement();
            Statement q=con.createStatement();
            ResultSet rs2=q.executeQuery("SELECT MEDNAME,QUANTITY FROM CART");
            while(rs2.next()){
            String g=rs2.getString("QUANTITY");
            String f=rs2.getString("MEDNAME");
                int z=t.executeUpdate("UPDATE MEDICINES SET STOCK=STOCK-"+g+" WHERE MEDNAME='"+f);
                    }
            }
            this.setVisible(false);
            C.setVisible(true);
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null,e.getMessage());
                }
        }
 else {
            JOptionPane.showMessageDialog(null,"Incorrect credentials");
            if(z==3){
                JOptionPane.showMessageDialog(null,"Error:\nSession ended. Please try again later !");
                new PAYMENT_GATEWAY().setVisible(false);
                new CUSTOMER_CART().setVisible(true);
            }
z++;
 }
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jButton6ActionPerformed
int y=1;
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         String a=jComboBox1.getSelectedItem().toString();
        String b=jComboBox2.getSelectedItem().toString();
       try{
            Class.forName("java.sql.DriverManager");
            Connection con1=DriverManager.getConnection("jdbc:mysql://localhost/ipproject","root","muruga123");
            Statement st8=con1.createStatement();
            ResultSet rs=st8.executeQuery("SELECT * FROM CREDITCARD WHERE CVV="+new String(jPasswordField1.getPassword()));
            if(rs.next()){
                int c=Integer.parseInt(rs.getString("EXPMM"));
                String d="";
                if(c<10) d="0".concat(c+"");
        if(jTextField2.getText().equalsIgnoreCase(rs.getString("CARDNO")) && a.equalsIgnoreCase(d) && b.equalsIgnoreCase(rs.getString("EXPYYYY"))){
            JOptionPane.showMessageDialog(null,"Payment successful");
            AFTER_PAYMENT C=new AFTER_PAYMENT();
             try{
                     Class.forName("java.sql.DriverManager");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/ipproject","root","muruga123");
            Statement st=con.createStatement();
            Statement ts=con.createStatement();
            String xe="";
            ResultSet sr=ts.executeQuery("SELECT * FROM ORDERS");
            if(sr.last()){
                sr.last();
                xe=sr.getString("ORDERID");
            }

                DefaultTableModel m1=(DefaultTableModel)C.jTable1.getModel();
                 
                ResultSet rs1=st.executeQuery("SELECT * FROM ORDERS WHERE ORDERID="+xe);
                if(rs1.next()){
                String st2=rs1.getString("ORDERID");
                String st3=rs1.getString("CUSNAME");
                String st4=rs1.getString("ORDERPRICE");
                String st5=rs1.getString("PLACEDATE");
                String st6=rs1.getString("DELIVERYDATE");
                String st7=rs1.getString("NOOFITEMS");
                

                m1.addRow(new Object[] {st2,st3,st4,st5,st6,st7});
                 
                }
            this.setVisible(false);
            C.setVisible(true);
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null,e.getMessage());
                }
            
        }
 else {
            JOptionPane.showMessageDialog(null,"Incorrect credentials");
            if(y==3){
                JOptionPane.showMessageDialog(null,"Error:\nSession ended. Please try again later !");
                new PAYMENT_GATEWAY().setVisible(false);
                new CUSTOMER_CART().setVisible(true);
            }
y++;
 }
           }
        }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected()){
            AFTER_PAYMENT C=new AFTER_PAYMENT();
             try{
                     Class.forName("java.sql.DriverManager");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/ipproject","root","muruga123");
            Statement st=con.createStatement();
            
                DefaultTableModel m1=(DefaultTableModel)C.jTable1.getModel();
               Statement ts=con.createStatement();
            String xe="";
            ResultSet sr=ts.executeQuery("SELECT * FROM ORDERS");
            if(sr.last()){
                sr.last();
                xe=sr.getString("ORDERID");
            }
                ResultSet rs1=st.executeQuery("SELECT * FROM ORDERS WHERE ORDERID="+xe);
                if(rs1.next()){
                String st2=rs1.getString("ORDERID");
                String st3=rs1.getString("CUSNAME");
                String st4=rs1.getString("ORDERPRICE");
                String st5=rs1.getString("PLACEDATE");
                String st6=rs1.getString("DELIVERYDATE");
                String st7=rs1.getString("NOOFITEMS");
                

                m1.addRow(new Object[] {st2,st3,st4,st5,st6,st7});
                
                }
            this.setVisible(false);
            C.setVisible(true);
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null,e.getMessage());
                }
           
          
        }
 else JOptionPane.showMessageDialog(null,"Please check the box to confirm your payment through cash at the time of delivery.");
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PAYMENT_GATEWAY().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    public static javax.swing.JButton jButton5;
    public static javax.swing.JButton jButton6;
    public static javax.swing.JButton jButton7;
    public static javax.swing.JButton jButton8;
    public static javax.swing.JCheckBox jCheckBox1;
    public static javax.swing.JComboBox jComboBox1;
    public static javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel11;
    public static javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanel2;
    public static javax.swing.JPasswordField jPasswordField1;
    public static javax.swing.JRadioButton jRadioButton1;
    public static javax.swing.JRadioButton jRadioButton2;
    public static javax.swing.JRadioButton jRadioButton3;
    public static javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}
