/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SIGN_IN.java
 *
 * Created on 9 Jun, 2018, 6:37:23 PM
 */

/**
 *
 * @author Manoharan
 */
import javax.swing.*;
import java.sql.*;
public class SIGN_IN_ADMIN extends javax.swing.JFrame {

    /** Creates new form SIGN_IN */
    public SIGN_IN_ADMIN() {
    

        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Abhishek's DRUG Emporium");

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 36));
        jLabel2.setForeground(new java.awt.Color(-65536,true));
        jLabel2.setText("SIGN IN");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(-16777216,true), 2, true));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 230, 140, 60);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18));
        jLabel3.setText("USERNAME :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 320, 120, 20);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(160, 320, 160, 22);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18));
        jLabel4.setText("PASSWORD : ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 370, 120, 24);

        jButton1.setBackground(new java.awt.Color(-16777216,true));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 18));
        jButton1.setForeground(new java.awt.Color(-65536,true));
        jButton1.setText("SIGN IN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(90, 520, 150, 33);

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 24));
        jLabel5.setText("NOT A USER YET ? ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(510, 340, 230, 100);

        jButton2.setBackground(new java.awt.Color(-16777216,true));
        jButton2.setFont(new java.awt.Font("SansSerif", 1, 18));
        jButton2.setForeground(new java.awt.Color(-14336,true));
        jButton2.setText("SIGN UP");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(550, 420, 120, 60);
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(160, 370, 160, 22);

        jButton4.setFont(new java.awt.Font("Dialog", 1, 18));
        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(670, 520, 110, 40);

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 24));
        jLabel6.setText("ADMIN");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(-16777216,true)));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 160, 90, 40);

        jButton5.setText("FORGOT PASSWORD ?");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(80, 470, 170, 30);

        jButton6.setIcon(new javax.swing.ImageIcon("C:\\IPPROJECT\\IPPROJECT\\images\\on button.png")); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(680, 0, 120, 120);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(160, 370, 160, 22);

        jCheckBox1.setText("SHOW PASSWORD");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(90, 420, 150, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\IPPROJECT\\IPPROJECT\\images\\pharmacy 1.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 570);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        new SIGN_UP_ADMIN_1().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new HOME().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String a=jTextField1.getText();
        String b=new String(jPasswordField1.getPassword()) ;
        ADMIN_HOME H=new ADMIN_HOME();
        try{
            Class.forName("java.sql.DriverManager");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/ipproject","root","muruga123");
            Statement st=con.createStatement();
            Statement st1=con.createStatement();
            String SQL="SELECT*FROM USERS WHERE USERNAME=\""+a+"\" AND PASSWORD=\""+b+"\" AND DEPT=\"ADMIN\"";
            ResultSet rs=st.executeQuery(SQL);
            if(rs.next()){
                JOptionPane.showMessageDialog(null,"Login Successful");
                String c=rs.getString("EMAILID");
            ResultSet rs1=st1.executeQuery("SELECT * FROM ADMIN WHERE ADMINMAIL='"+c+"'");
            if(rs1.next()){
            String d=rs1.getString("ADMINNAME");
            H.jLabel2.setText(d);
            H.setVisible(true);
            this.setVisible(false);
               }
            }
        else{
                JOptionPane.showMessageDialog(null,"Login Unsuccessful");
                jTextField1.setText("");
                jPasswordField1.setText("");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
            new SIGN_IN_ADMIN().setVisible(true);
            this.setVisible(false);
        }

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new FORGOT_PASSWORD_ADMIN().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
       System.exit(0);
}//GEN-LAST:event_jButton6ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected()){
            String a=new String(jPasswordField1.getPassword());
        jPasswordField1.setVisible(false);
        jTextField2.setVisible(true);
        jTextField2.setText(a);
        }
 else{
            jPasswordField1.setVisible(true);
 }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SIGN_IN_CUSTOMER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}
